--select status from ClientsDB where UserName = 'alen1'
--update ClientsDB set Status ='Offline' where UserName = 'alen'
--update ClientsDB set Status ='Offline'
--select * from ClientsDB where ID = 6
--select status from ClientsDB where UserName = @userName
--select ID from ClientsDB where UserName = 'alen'
--insert MessagesDB values (6, 'alen', 'demo message', 'date goes here', 'false', 'false')
--select *from ClientsDB where UserName = 'alen3'
--select * from MessagesDB where Message like '%da%'
--select * from ClientsDB where [Logged/Last Logged] = 'alen'
--update ClientsDB set Status ='online', [Logged/Last Logged] = 'a' where UserName = @userName
--update ClientsDB set [Logged/Last Logged]='ada'where UserName = 'adsa'
--select * from MessagesDB where Date like '%16:55:55%'
select * from MessagesDB where IsPrivate = 'alen3'